name: "CI"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    env:
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18@sha256:3bb77a07b9ce8b8de0fe6d9b063adf20b9cca1068a1bcdc054cac71a69ce0ca6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sample_db
        ports:
          - 15432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 24
      - name: install libpq-dev
        run: sudo apt-get install -y libpq-dev
      - name: Install Infisical CLI
        run: |
          curl -1sLf https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh | sudo -E bash
          sudo apt-get -o DPkg::Lock::Timeout=60 install -y infisical

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.8"
          bundler-cache: true
          working-directory: apps/backend

      - name: Mark repo as safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: enable corepack
        run: corepack enable

      - name: yarn set v4
        run: yarn set version stable

      - name: yarn install
        run: yarn install

      - name: yarn check
        run: yarn check
        
