name: "CI"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  ci:
    env:
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: Infisical/secrets-action@v1.0.9
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          project-slug: example-project-p-e38
          project id: 7f77ea6e-c225-4c3a-844e-039f6467f07f
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - name: install libpq-dev
        run: sudo apt-get install -y libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          working-directory: apps/backend

      - name: Mark repo as safe for git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: enable corepack
        run: corepack enable

      - name: yarn set v4
        run: yarn set version stable

      - name: yarn install
        run: yarn install

      - name: yarn check
        run: yarn check
